### ISSUE TITLE
If npm failed to install the plugin whole step still can successful

### ISSUE THREAD

**Issue by Makishima** [bitrise-steplib/steps-cordova-archive#44]
In my case, there is a custom plugin that was unavailable during installation. But the step is still processed and builds up applications that do not include plugin.
The step should fail if it cannot install plugins.

<details>
<summary>Beginning of the step's log</summary>
Discovered plugin "XXX". Adding it to the project

Failed to restore plugin "XXX". You might need to try adding it again. Error: Error: Command failed with exit code 1: npm view XXX --json
npm ERR! code E404
npm ERR! 404 'XXX' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm ERR! 404 
npm ERR! 404  'XXX@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vagrant/.npm/_logs/2020-10-15T13_57_49_715Z-debug.log
{
  "error": {
    "code": "E404",
    "summary": "'XXX' is not in the npm registry.\nYou should bug the author to publish it\n(or use the name yourself!)\n\nNote that you can also install from a\ntarball, folder, http url, or git url.",
    "detail": "\n 'XXX@latest' is not in the npm registry.\nYou should bug the author to publish it (or use the name yourself!)\n\nNote that you can also install from a\ntarball, folder, http url, or git url."
  }
}
</details>

**Comment by bitce** [comment]
Hi @Makishima! Thanks for the report! Can you include an URL to the build here please?

**Comment by Makishima** [comment]
Hey, @bitce I'm not sure that able to post our whole log. Which info do you want from it?

**Comment by non-binary** [comment]
@Makishima This log will only be accessible to support folks as long as the project is private.

**Comment by Makishima** [comment]
Here we go https://app.bitrise.io/build/b896a71929d1f5aa#?tab=log
You can look for the end of step (5) Cordova platform add or beginning of step (7) cordova-archive@2

**Comment by bitce** [comment]
Hi @Makishima, sorry for the delay here. Strangely we can not locate this build's information, can you enable Support User access for us in the app's Settings?

**Comment by Makishima** [comment]
@bitce Done, please check it

**Comment by bitce** [comment]
Thanks! So this doesn't seem to be related to this repository or step, this seems to happen because you invoke these commands from a Script step.
It fails because NPM does not return a non-0 exit code which is strange. Is pulling these dependencies prior to running `cordova add` an option? That might be a solution here.

**Comment by Makishima** [comment]
Why is it not related? 
Let's check step №7
![изображение](https://user-images.githubusercontent.com/5548003/98653896-a5bd4d00-234e-11eb-84cd-ec683a4fb2c9.png)
And step is marked as succesful
![изображение](https://user-images.githubusercontent.com/5548003/98653982-c5ed0c00-234e-11eb-9eb3-762824ad0893.png)

**Comment by bitce** [comment]
No that's completely correct, apologies for the confusion. Taking a look!

**Comment by mjones-droid** [comment]
Hey @Makishima!

The thing that's interesting to me about this is that the build itself succeeds. The reason that the step shows a success is because, despite not having the plugin, the Cordova archive still completes. 

If I go to the apps and artifacts tab I see that there's an APK and an IPA. Cordova is completing this build successfully. 

We don't do anything special with Cordova. We just listen to whether it reports a success or not. In this case, it is. 

Are you sure you're even using this plugin inside the code? I would think that if your code truly relied on it the build would fail. Alternatively, did you check the plugin into source control?

Either way, for some reason Cordova is reporting a success. As long as Cordova gives Bitrise the thumbs up, there's not a lot we can do to determine success or failure beyond that. We rely on the Cordova exit code.

**Comment by Makishima** [comment]
>Are you sure you're even using this plugin inside the code?

Yep, we faced this situation when our BLE-devices cannot connect to this build

> As long as Cordova gives Bitrise the thumbs up, there's not a lot we can do to determine success or failure beyond that.

Is there chance that you could scan log foк certain messages like `ERR`, `ERROR`, etc. and somehow show that there is potention problem after step is over?

**Comment by mjones-droid** [comment]
@Makishima 

The problem with a behavior change like that is we may break builds for someone else in the process. 

It appears that the error didn't happen during the actual `cordova compile `command but rather the `cordova prepare` command before it. 

My suggestion is to flip `Should 'cordova prepare' be executed before 'cordova compile'`? to false in the archive step. Then add a script step right before it with `cordova "prepare" "ios" "android"`. This should return a bad exit code and cause the step to fail, which in turn would cause the rest of the workflow to fail.
